name: Fetch IPA URL and Update JSON

on:
  workflow_dispatch:  # Allows for manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  fetch-ipa:
    runs-on: ubuntu-latest
    steps:
      - name: Get IPA URL
        id: get_ipa_url
        run: |
          IPA_URL=$(curl -s "https://api.github.com/repos/whoeevee/EeveeSpotify/releases/latest" | 
          jq -r '.assets[] | select(.name | endswith(".ipa")) | .browser_download_url')
          echo "ipa_url=$IPA_URL" >> $GITHUB_ENV

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Verify IPA URL
        run: |
          echo "Fetched IPA URL: ${{ env.ipa_url }}"

      - name: Update sidestore.json
        run: |
          # Print before modification for debugging
          cat sidestore.json  
          # Update the downloadURL with the fetched IPA URL
          jq --arg ipa_url "${{ env.ipa_url }}" '.apps[0].downloadURL = $ipa_url' sidestore.json > temp.json
          # Move the updated file back to sidestore.json
          mv temp.json sidestore.json
          # Print after modification to confirm the change
          cat sidestore.json  

      - name: Check for Changes and Commit if Needed
        run: |
          # Check if there are changes in sidestore.json
          if git diff --exit-code sidestore.json; then
            echo "No changes detected in sidestore.json, skipping commit."
          else
            echo "Changes detected, committing..."
            git config --local user.email "niravraval34@gmail.com"
            git config --local user.name "Nirav-raval"
            git add sidestore.json
            git commit -m "Update downloadURL with latest IPA file URL"
            git push
          fi
