name: Fetch IPA URL and Update JSON

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  fetch-ipa:
    runs-on: ubuntu-latest
    steps:
      - name: Get IPA URL, Version, and Size
        id: get_ipa_url
        run: |
          # Fetch the latest IPA URL
          IPA_URL=$(curl -s "https://api.github.com/repos/whoeevee/EeveeSpotify/releases/latest" | 
          jq -r '.assets[] | select(.name | endswith(".ipa")) | .browser_download_url')
          
          if [ -z "$IPA_URL" ]; then
            echo "Error: IPA URL not found."
            exit 1
          fi

          # Extract version from URL using regex
          VERSION=$(echo "$IPA_URL" | grep -oP 'EeveeSpotify-\K[\d.]+(?=\.ipa)')

          if [ -z "$VERSION" ]; then
            echo "Error: Version not extracted from URL."
            exit 1
          fi

          # Fetch file size (in bytes) from asset information
          SIZE=$(curl -s "https://api.github.com/repos/whoeevee/EeveeSpotify/releases/latest" | 
          jq '.assets[] | select(.name | endswith(".ipa")) | .size')

          if [ -z "$SIZE" ]; then
            echo "Error: File size not found."
            exit 1
          fi

          # Export environment variables with proper escaping
          echo "ipa_url=${IPA_URL}" >> $GITHUB_ENV
          echo "version=${VERSION}" >> $GITHUB_ENV
          echo "size=${SIZE}" >> $GITHUB_ENV

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Verify Extracted Variables
        run: |
          echo "Fetched IPA URL: ${{ env.ipa_url }}"
          echo "Extracted Version: ${{ env.version }}"
          echo "File Size: ${{ env.size }} bytes"

      - name: Update sidestore.json
        run: |
          # Print before modification for debugging
          echo "Before Update:"
          cat sidestore.json || echo "sidestore.json not found."

          # Update JSON file
          jq --arg ipa_url "${{ env.ipa_url }}" \
             --arg version "${{ env.version }}" \
             --argjson size "${{ env.size }}" \
             '.apps[0].downloadURL = $ipa_url | 
              .apps[0].version = $version | 
              .apps[0].size = $size |
              .apps[0].versions[0].downloadURL = $ipa_url |
              .apps[0].versions[0].version = $version |
              .apps[0].versions[0].size = $size' \
             sidestore.json > temp.json

          # Replace the original file
          mv temp.json sidestore.json

          # Print updated file for verification
          echo "After Update:"
          cat sidestore.json

      - name: Check for Changes and Commit if Needed
        run: |
          # Check for changes in sidestore.json
          if git diff --quiet sidestore.json; then
            echo "No changes detected, skipping commit."
          else
            echo "Changes detected, committing..."
            git config --local user.email "niravraval34@gmail.com"
            git config --local user.name "Nirav-raval"
            git add sidestore.json
            git commit -m "Update sidestore.json with latest IPA details"
            git push
          fi
