name: Fetch IPA URL and Update JSON

on:
  workflow_dispatch:

jobs:
  fetch-ipa:
    runs-on: ubuntu-latest
    steps:
      - name: Get IPA URL
        id: get_ipa_url
        run: |
          IPA_URL=$(curl -s "https://api.github.com/repos/whoeevee/EeveeSpotify/releases/latest" | 
          jq -r '.assets[] | select(.name | endswith(".ipa")) | .browser_download_url')
          echo "ipa_url=$IPA_URL" >> $GITHUB_ENV
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Verify IPA URL
        run: |
          echo "Fetched IPA URL: ${{ env.ipa_url }}"
      - name: Update sidestore.json
        run: |
          # Print original sidestore.json for debugging
          cat sideload/sidestore.json  
          # Update the downloadURL with the fetched IPA URL
          jq --arg ipa_url "${{ env.ipa_url }}" '.apps[0].downloadURL = $ipa_url' sideload/sidestore.json > temp.json
          # Move the temp file back to sideload/sidestore.json to finalize changes
          mv temp.json sideload/sidestore.json
          # Print modified sidestore.json for confirmation
          cat sideload/sidestore.json  
      - name: Commit Changes
        run: |
          git config --local user.email "niravraval34@gmail.com"
          git config --local user.name "Nirav-raval"
          git add sideload/sidestore.json
          git commit -m "Update downloadURL with latest IPA file URL"
          git push
