name: Fetch IPA URL and Update JSON

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  fetch-ipa:
    runs-on: ubuntu-latest
    steps:
      - name: Get IPA URL, Version, and Size
        id: get_ipa_url
        run: |
          # Fetch the latest IPA URL
          IPA_URL=$(curl -s "https://api.github.com/repos/whoeevee/EeveeSpotify/releases/latest" | 
          jq -r '.assets[] | select(.name | endswith(".ipa")) | .browser_download_url')

          if [ -z "$IPA_URL" ]; then
            echo "Error: IPA file URL not found in the release assets."
            exit 1
          fi
          echo "Fetched IPA URL: $IPA_URL"

          # Extract version from URL (generalized for any version format)
          VERSION=$(echo "$IPA_URL" | grep -oP 'EeveeSpotify-\K[^-]+(?=\.ipa)')
          
          if [ -z "$VERSION" ]; then
            echo "Error: Version could not be extracted from the IPA file URL."
            exit 1
          fi
          echo "Extracted Version: $VERSION"

          # Fetch the file size (in bytes)
          SIZE=$(curl -s "https://api.github.com/repos/whoeevee/EeveeSpotify/releases/latest" | 
          jq '.assets[] | select(.name | endswith(".ipa")) | .size')

          if [ -z "$SIZE" ]; then
            echo "Error: File size not found for the IPA file."
            exit 1
          fi
          echo "File Size: $SIZE bytes"

          # Sanitize and export environment variables
          {
            echo "ipa_url<<EOF"
            echo "$IPA_URL"
            echo "EOF"
            echo "version=$VERSION"
            echo "size=$SIZE"
          } >> $GITHUB_ENV

      - name: Verify Extracted Variables
        run: |
          echo "IPA URL: ${{ env.ipa_url }}"
          echo "Version: ${{ env.version }}"
          echo "Size: ${{ env.size }} bytes"
